### PR TITLE
More reworking on scripts; now builds a disk image that gets to a command prompt.

### LINKED ISSUE #17: Build Scripts: Rework
A reorganization and sorting of scripts done by @sweetaibelle: 

I linked the pull requests to it for ease of finding them.

### PR DESCRIPTION
**Pull request by sweetaibelle**
This combines several of the scripts, and adds a few helper scripts, as well as symbolic links to the linux and toybox configs elsewhere in the project.

It now copies in all the needed files from fdd / fdd/fs that it doesn't create, copies the binaries to the right places, creates symbolic links for toybox, and boots.

The helper scripts let you run all the numbered scripts by just running build.sh, delete everything the scripts created with clean.sh, and launch it in qemu, and I cobbled together a quick readme in the script folder.

### CODE REVIEW

**Comment by sweetaibelle** [comment]
Looks like there are two conflicts, but you can probably resolve them easily enough. I had to modify init and inittab to get it to boot, and I think you fixed them since then...

**Comment by sweetaibelle** [comment]
Went ahead and fixed the conflict. You'll probably want to squash the commits when merging...

**Comment by sweetaibelle** [comment]
Looks like a broken symbolic link, too (because the kernel version updated since when I started working on it). I'll fix that in a minute.

**Review by kkarhan — APPROVED** [review]
thanks for your contribution - looks good...

**Comment by kkarhan** [comment]
@sweetaibelle I added you to the "Maintainers" and configured permissions properly, so that should allow you to directly commit to the git.
 Tho feel free to branch as need be...

**Comment by sweetaibelle** [comment]
@kkarhan 
Thanks!

You may very well see me making prs. then merging them myself some of the time...

While I didn't touch the scripts you've been using, just the ones in scripts, you might want to grab the same bit for adding toybox symbolic links I used in mine:
```
# Create symlinks for all toybox commands
for i in $(./toybox); do ln -s toybox $i; done
```

That's actually why running toybox returns all the names of the programs, I think...

**Pull request merged**
